### ISSUE TITLE
chrome默认背景图片不展示

### ISSUE THREAD

**Issue by linwx611** [roomanl/typecho-theme-win10explorer#2]
问题如题目所言，

以及 请问 能否添加 js，单机关闭按钮，弹出对话框，是否真的离开网页等等。

**Comment by roomanl** [comment]
> 问题如题目所言，
> 
> 以及 请问 能否添加 js，单机关闭按钮，弹出对话框，是否真的离开网页等等。

要显示默认背景请把style.css第68行的注释去掉
要要关闭代码可以在js/index.js里面最后面加上以下代码
`$('.right-top img').eq(2).on('click',function(){
   //这里编写对话框等代码
})`
上面代码中eq(0)是右上角第一个按钮的点击事件，以此类推eq(1)，eq(2)就是右上角第2、3个按钮的点击事件。
